### ISSUE TITLE
Training Data

### ISSUE THREAD

**Issue by ruoshiliu** [hotshotco/Hotshot-XL#17]
Hi, thanks a lot for the model release! I'm trying to find out more info regarding the training dataset but couldn't find it. What's the size of the training dataset? Roughly how many video clips is the model trained on? Thanks in advance!

**Comment by aakashs** [comment]
hi! Trained on an internal dataset of tens of millions of clips.

**Comment by dydxdt** [comment]
Thanks for your reply. Do you mean the number of finetuned dataset is 10M？I'm not sure the amount of pretrained dataset and finetuned dataset, since I have a few data and not sure whether it will work if finetuning on a few data. Would you minding sharing? Many thanks! @aakashs
