### ISSUE TITLE
Minimum required VRAM?

### ISSUE THREAD

**Issue by blueangel1313** [hotshotco/Hotshot-XL#2]
Hello! Loving this model. I was able to run inference on a 40GB A100. Was curious if you could share more about the minimum required VRAM to inference this model? Thx!

**Comment by blueangel1313** [comment]
reporting back. I was able to run inference with a T4.

**Comment by phineas-pta** [comment]
more exact number is 11 gb vram

**Comment by Mozer** [comment]
Geforce 3060 12 GB is working fine for 672x384 and 8 frames. Peak VRAM usage that I see task manager is 10.5 GB
