### ISSUE TITLE
Merge with diffusers

### ISSUE THREAD

**Issue by sepal** [hotshotco/Hotshot-XL#20]
First, thanks for this very cool model!

Secondly, I wonder if it would make sense to merge hotshot pipeline into [diffusers](https://github.com/huggingface/diffusers), since Hotshot-XL seems "just" like another diffusion pipeline.

**Comment by aakashs** [comment]
hello! We are looking into it :)

**Comment by sepal** [comment]
Very cool. Let me know if you need help!
