### ISSUE TITLE
[Question] What are recommended parameters for transforming existing 1920x1080 footage?

### ISSUE THREAD

**Issue by vedantroy** [hotshotco/Hotshot-XL#22]
Hi! I'm trying to transform some existing footage that has resolution 1920x1080 and I'm wondering what are the correct parameters to set during inference. I.e., I know there's width/height, crop top/left, and target width/target height.

My intuition is to
- set target_width/target_height to  672 x 384 (most closely matches 1920x1080)
- set og_width/og_height to 1920x1080
- Resize the footage to 672x384 before feeding it into the model

Does this sound correct?

**Comment by aakashs** [comment]
For usage with ControlNet @ inference? Yes that is correct!
