### ISSUE TITLE
Fine-tuning time estimation

### ISSUE THREAD

**Issue by bonlime** [hotshotco/Hotshot-XL#3]
Hi! thanks for a very interesting model released. Could you share how many GPU hours (+GPU used) you've spent to get the current model? 

Also what data did you use for training? Modelscope or something without watermarks?

**Comment by aakashs** [comment]
Hi! Thanks

Don't know exactly how many GPU hours but it was definitely *a lot* + lots of GPUs. 

Modelscope is awesome, but Hotshot-XL is a totally different architecture/unrelated.
