### ISSUE TITLE
EinopsError:

### ISSUE THREAD

**Issue by XTRMsavage** [hotshotco/Hotshot-XL#32]
HI, When I am trying to do the following I am getting the error below. How to resolve it?

Error while processing rearrange-reduction pattern "(b f) c h w -> b c f h w". Input tensor shape: torch.Size([2, 320, 8, 64, 64]). Additional info: {'b': 2}. Expected 4 dimensions, got 5

<img width="1388" alt="image" src="https://github.com/hotshotco/Hotshot-XL/assets/90519573/d0c0ce87-9625-4b62-8c4e-387bca09e068">

<img width="803" alt="image" src="https://github.com/hotshotco/Hotshot-XL/assets/90519573/cd2e1f03-a3e7-42db-a451-d8f362478228">

**Comment by Zyablik1989** [comment]
> HI, When I am trying to do the following I am getting the error below. How to resolve it?
> 
> Error while processing rearrange-reduction pattern "(b f) c h w -> b c f h w". Input tensor shape: torch.Size([2, 320, 8, 64, 64]). Additional info: {'b': 2}. Expected 4 dimensions, got 5
> 


I got the same thing. It's happen because you have no SDXL model in memory. 

It's either when you just restarted A1111 and didn't generated a single (non-animated) image, 
or when you tried to generate a gif, but got a CUDA outOfMemoryError and SDXL model went unloaded
