### ISSUE TITLE
How do we cite the model?

### ISSUE THREAD

**Issue by jinga-lala** [hotshotco/Hotshot-XL#33]
Please provide the bibtex pointing to the authors.

**Comment by aakashs** [comment]
We added CITATION.cff to the repo. You can copy the bibtex from the sidebar in Github. Thank you :)
<img width="589" alt="image" src="https://github.com/hotshotco/Hotshot-XL/assets/2073966/3f96166d-41d3-42b3-903a-a49f492861bb">


@software{Mullan_Hotshot-XL_2023,
author = {Mullan, John and Crawbuck, Duncan and Sastry, Aakash},
license = {Apache-2.0},
month = oct,
title = {{Hotshot-XL}},
url = {https://github.com/hotshotco/hotshot-xl},
version = {1.0.0},
year = {2023}
}
