### ISSUE TITLE
lora not work

### ISSUE THREAD

**Issue by 823863429** [hotshotco/Hotshot-XL#37]
Thank you for your outstanding work. I specified a lora file when generating, but the generated content has nothing to do with the style of lora. Is there any problem when I use it? lora is trained according to sdxl. Here's how I use it：
python inference.py \
  --prompt="a camel is smoking, hd, high quality" \
  --output="output.gif" \
  --lora="/content/hotshot-xl/3d_keai_2.0.safetensors"

**Comment by aakashs** [comment]
Hi, you may have to use your lora's corresponding tokens in the prompt to obtain optimal results? Hard to know based on information provided - hotshot-xl definitely works with LORAs. 

Perhaps ask in the Discord and someone can help!
