### ISSUE TITLE
Finetune, cuda out of memory

### ISSUE THREAD

**Issue by xiefan233** [hotshotco/Hotshot-XL#47]
I am using your code to make Finetune, but "cuda out of memory" is displayed. What is the memory space required by Finetune? I used an A100 with 40GB of RAM. I think the reason is that the size of the picture is too large (512). Is there a smaller picture size available from Finetune?

**Comment by johnmullan** [comment]
I responded to this here
https://github.com/hotshotco/Hotshot-XL/issues/45#event-11402451913

It will be a challenge to fine tune on a A100 40gb at that resolution.
